$APPS = @( 
		"7zip.7zip",
		"AgileBits.1Password",
		"Rufus.Rufus",
		"Giorgiotani.Peazip",
		"REALiX.HWiNFO",
		"hwmonitor",
		"Mozilla.Firefox",
		"Nota.Gyazo",
    "RODE.RODECasterVirtualDeviceDriver",
		"XP89DCGQ3K6VLD" #PowerToys
		)

$DEV= @(
    "Microsoft.PowerShell",
    "Microsoft.WindowsTerminal",
		"Microsoft.VisualStudioCode",
		"Oracle.JavaRuntimeEnvironment",
		"GitHub.cli",
		"9P7KNL5RWT25", #SysInternals
		"WinSCP.WinSCP",
		"Notepad++.Notepad++",
		"Microsoft.DotNet.DesktopRuntime.7",
    "wez.wezterm",
		"Git.Git",
    "Neovim.Neovim"
)

$GAME= @(
		"ElectronicArts.EADesktop",
		"Discord.Discord",
		"RiotGames.LeagueOfLegends.NA",
		"Valve.Steam",
		"TeamSpeakSystems.TeamSpeakClient",
    "Blizzard.BattleNet",
    "Blitz.Blitz"
)
