APPS=(
    "visual-studio-code"
    "git"
    "gh"
    "firefox"
    "1password"
    "1password-cli"
    "discord"
    "slack"
    "cyberduck"
    "vlc"
    "steam"
    "sevenzip"
    "aerospace"
    "logi-options+"
)

DEV_TOOLS=(
    "jesseduffield/lazygit"
    "bat"
    "curlie"
    "gh"
    "git"
    "go"
    "lazygit"
    "git-delta"
    "node"
    "nikitabobko/tap"
)

TERMINAL_TOOLS=(
    "eza"
    "fd"
    "ffmpegthumbnailer"
    "fzf"
    "imagemagick"
    "jq"
    "neovim"
    "poppler"
    "posting"
    "ripgrep"
    "starship"
    "thefuck"
    "tlrc"
    "tmux"
    "wget"
    "xh"
    "yazi"
    "zoxide"
    "zsh-autosuggestions"
    "zsh-syntax-highlighting"
    "wezterm"
)

FONTS=(
    "font-jetbrains-mono"
    "font-symbols-only-nerd-font"
)
